### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by ionas** [makallio85/yaml-route#2]
I like it, but does it do validation of "at least required keys" or could it generate invalid routes setups?

**Comment by makallio85** [comment]
At this point, as exception handling is not at required level, no. It throws notices about missing array indexes, that should be visible though.

**Comment by makallio85** [comment]
Validation has improved quite much now. Please see latest version for updates.

**Comment by makallio85** [comment]
Ill be closing this for now, please feel free to send more feedback, if you find any problems.
